!**** *namelist* *TRACTL* - controls options to run the tracer transport
!                                                                       
!     J. Feichter, MI, September 1990, original source
!                                                                       
!      name     type      purpose                                       
!      ----     ----      -------                                       
!                                                                       

NAMELIST /tractl/                                                     &
& ntrac, lslt, lppxt, lhtrac, ntcode, nfix, nfixt, lxtvdiff, lxtconv, &
& lwetdep, sxtini, sxtemi, vdrydep, sxtsink

!     ------------------------------------------------------------------
