#!/bin/sh
#
set -e
#
AFTER=after
#
DPATH=`dirname $1`
DFILE=`basename $1`
#
if [ ! -f $DPATH/$DFILE ] ; then
  echo "File $DPATH/$DFILE not found"
  exit
fi
#
$AFTER $DPATH/${DFILE} ${DFILE}.abm  << EOA
 &SELECT TYPE=20, MEAN=1, GRIB=1 &END
EOA
#
exit
