#!/bin/sh
#
# This script convert ECHAM4 initial files from
# CRAY pure binary format to netCDF
#
# Uwe Schulzweida, MPI, July 1999
#
#
set -ex
RES=106
MONS="jan apr jul oct"
#MONS="jan"
#
for MON in $MONS ; do
#
INI4POOL=/export/home/m214003/DATA/INI/CRAY/ECHAM4/T${RES}/
INI4POOLNC=/export/home/m214003/DATA/INI/NC/ECHAM4/T${RES}/
#
SPECFILE=t${RES}${MON}.semi73
SURFFILE=${MON}${RES}m
#
if [ $RES -eq 30 ] ; then HOPT="-t${INI4POOL}${SPECFILE}" ; fi
#
#../bin/inispec2anc ${INI4POOL}${SPECFILE} ${SPECFILE}.nc
#ncdump ${SPECFILE}.nc > ${SPECFILE}.nc.cdl
#cp ${SPECFILE}.nc  ${INI4POOLNC}
#rm ${SPECFILE}.nc
#chmod 644 ${INI4POOLNC}${SPECFILE}.nc 
#
../bin/inisurf2snc $HOPT ${INI4POOL}${SURFFILE}.new ${SURFFILE}.nc
ncdump ${SURFFILE}.nc > ${SURFFILE}.nc.cdl
cp ${SURFFILE}.nc ${INI4POOLNC}
rm ${SURFFILE}.nc
chmod 644 ${INI4POOLNC}${SURFFILE}.nc
#
done
#
exit
